// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADefault: typeof import('./src/components/aside/aDefault.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    Aside: typeof import('./src/components/layout/aside.vue')['default']
    Banner: typeof import('./src/components/discover/recommend/banner.vue')['default']
    CenterContoller: typeof import('./src/components/layout/footer/centerContoller.vue')['default']
    Collector: typeof import('./src/components/playlistDetail/collector.vue')['default']
    Comment: typeof import('./src/components/player/comment.vue')['default']
    ContentMenu: typeof import('./src/components/contentMenu.vue')['default']
    DetailHeader: typeof import('./src/components/playlistDetail/DetailHeader.vue')['default']
    DiscoverNav: typeof import('./src/components/discover/discoverNav.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import("element-plus/es/el-card")["default"];
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImg: typeof import("element-plus/es")["ElImg"];
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import("element-plus/es/el-link")["default"];
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import("element-plus/es/el-menu")["default"];
    ElMenuItem: typeof import("element-plus/es/el-menu-item")["default"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Left: typeof import('./src/components/player/left.vue')['default']
    LeftButtons: typeof import('./src/components/layout/footer/leftButtons.vue')['default']
    LeftInfo: typeof import('./src/components/layout/footer/leftInfo.vue')['default']
    Login: typeof import('./src/components/loginPage/login.vue')['default']
    LoginPage: typeof import('./src/components/loginPage.vue')['default']
    Lyric: typeof import('./src/components/player/lyric.vue')['default']
    MusicListComp: typeof import('./src/components/playlistDetail/musicListComp.vue')['default']
    MyMusic: typeof import('./src/components/aside/myMusic.vue')['default']
    NewMusic: typeof import('./src/components/discover/recommend/newMusic.vue')['default']
    Player: typeof import('./src/components/player.vue')['default']
    PlayerCenter: typeof import('./src/components/player/playerCenter.vue')['default']
    PlayerLeft: typeof import('./src/components/player/playerLeft.vue')['default']
    PlayerRight: typeof import('./src/components/player/playerRight.vue')['default']
    PlaylistComment: typeof import('./src/components/playlistDetail/playlistComment.vue')['default']
    RankList: typeof import("./src/components/discover/recommend/rankList.vue")["default"];
    RecemmendPlaylist: typeof import('./src/components/discover/recommend/recemmendPlaylist.vue')['default']
    Register: typeof import('./src/components/loginPage/register.vue')['default']
    RightButtons: typeof import('./src/components/layout/footer/rightButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPlaylist: typeof import('./src/components/aside/userPlaylist.vue')['default']
  }
}

export {}
