// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADefault: typeof import('./src/components/aside/aDefault.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    Aside: typeof import('./src/components/layout/aside.vue')['default']
    CollectPlaylist: typeof import('./src/components/aside/collectPlaylist.vue')['default']
    ContentMenu: typeof import('./src/components/contentMenu.vue')['default']
    CreatedPlaylist: typeof import('./src/components/aside/createdPlaylist.vue')['default']
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElAutocomplete: typeof import('element-plus/es/el-autocomplete')['default']
    ElAvatar: typeof import('element-plus/es/el-avatar')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCard: typeof import("element-plus/es/el-card")["default"];
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElDivider: typeof import('element-plus/es/el-divider')['default']
    ElDropdown: typeof import("element-plus/es/el-dropdown")["default"];
    ElDropdownItem: typeof import("element-plus/es/el-dropdown-item")["default"];
    ElDropdownMenu: typeof import("element-plus/es/el-dropdown-menu")["default"];
    ElFooter: typeof import('element-plus/es/el-footer')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElIcon: typeof import('element-plus/es/el-icon')['default']
    ElLink: typeof import("element-plus/es/el-link")["default"];
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElMenu: typeof import("element-plus/es/el-menu")["default"];
    ElMenuItem: typeof import("element-plus/es/el-menu-item")["default"];
    ElScrollbar: typeof import('element-plus/es/el-scrollbar')['default']
    ElSlider: typeof import("element-plus/es/el-slider")["default"];
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyMusic: typeof import('./src/components/aside/myMusic.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
